[package]
name = "flathub-hooks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
clap = { version = "4.1.11", features = ["derive"] }
diff = "0.1.13"
elementtree = "1.2.3"
env_logger = "0.10.0"
flate2 = "1.0.25"
log = "0.4.17"
ostree = { version = "0.17.0", features = ["v2021_5"] }
reqwest = { version = "0.11.13", features = ["json", "blocking"] }
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
